backend:
  name   : git-gateway
  branch : master

media_folder : static/img
public_folder : /img

collections:
  - name : "blog"
    label : "Blog"
    folder : "content/blog"
    create : true
    slug : "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor :
      preview : true
    fields :
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name : "settings"
    label : "Settings"
    files : 
      - label : "Contact Info"
        name : "contact_info"
        file : "site/settings/contact_info.json"
        fields :
          - { label : 'Phone', name: 'phone', widget: 'string' }
          - { label : 'Email', name: 'email', widget: 'string', required: false }
          - label : 'Address'
            name: 'address' 
            widget: 'object' 
            required : false
            fields : 
              - { label: 'Street' , name: 'street', widget : 'string', required : false }
              - { label: 'Street2' , name: 'street2', widget : 'string', required: false }
              - { label: 'City' , name: 'city', widget : 'string' , required : false}
      - label : "Config Details"
        name : "config_details"
        file : "site/settings/config_details.json"
        fields :
          - { label: "Company Name" ,  name : "company_name", widget: "string"}
          - { label: "Company Tag Line" , name : "company_tag_line", widget: "string" }